image: Visual Studio 2022
install:
- set QTHOME=C:\Qt\6.8.1\\msvc2022_64
- set BUILDDIR=build-release
- set PATH=%QTHOME%\bin;%PATH%
build_script:
- '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64'
- mkdir %BUILDDIR%
- cd /d %BUILDDIR%
- C:\Qt\6.8.1\\msvc2022_64\bin\qmake -spec win32-msvc -Wall ..\src\tableau-log-viewer.pro
- nmake
